branch-defaults:
  default:
    environment: x23219203-flowersdirect-app-env
    group_suffix: null
global:
  application_name: x23219203-flowersdirect-app
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.9
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
