# Generated by Django 2.1.15 on 2024-03-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20240312_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_amount_paid',
            field=models.BooleanField(default=False),
        ),
    ]
