# Generated by Django 4.2.11 on 2024-04-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='eir_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
