# Generated by Django 4.2.11 on 2024-04-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_alter_ordermodel_eir_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_order_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
