# Generated by Django 4.2.11 on 2024-04-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_ordermodel_is_order_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='is_amount_paid',
            field=models.BooleanField(default=True),
        ),
    ]
